server:
  port: 8080
  servlet:
    context-path: /awsome-pizza
spring:
  application:
    name: awsome-pizza
  datasource:
    url: jdbc:h2:mem:awsomepizza;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    com.simocaccia.awsomepizza: DEBUG
  headers:
    enabled: false
    list: content-type, user-agent, accept, host
