INSERT INTO PIZZA_ORDER (items, status) VALUES ('MARGHERITA', 'ACCEPTED');
INSERT INTO PIZZA_ORDER (items, status) VALUES ('MARGHERITA,ORTOLANA,PROSCIUTTO', 'ACCEPTED');
INSERT INTO PIZZA_ORDER (items, status) VALUES ('MARGHERITA', 'ACCEPTED');
INSERT INTO PIZZA_ORDER (items, status) VALUES ('ORTOLANA', 'STARTED');
INSERT INTO PIZZA_ORDER (items, status) VALUES ('PROSCIUTTO', 'COMPLETED');